#!/bin/bash

all_name='[ALL]'
mode=library

d_artist_composer() {
	cat <(mpc list artist) <(mpc list composer) | sort -f | sed '/^$/d' | dmenu -p Artist/Composer: "${dmenu_args[@]}"
}

d_album() {
    local artist="$1"
    local albums

    mapfile -t albums < <(cat <(mpc list album composer "$artist") <(mpc list album artist "$artist"))
    if (( ${#albums[@]} > 1 )) ; then
        {
            printf '%s\n' "$all_name"
            printf '%s\n' "${albums[@]}" | sort -f
        } | dmenu -p Album: "${dmenu_args[@]}"
    else
        # We only have one album, so just use that.
        printf '%s\n' "${albums[0]}"
    fi
}

d_playlist() {
    local format="%position%[[ - %title%][ - %album%][ - %composer% | - %artist%]] | [ - %file%]"
    local track

    track=$(mpc playlist -f "$format" | dmenu -p Track: "${dmenu_args[@]}")
    printf '%s' "${track%% *}"
}

i=2

for arg do
    if [[ $arg == :: ]]; then
        dmenu_args=( "${@:$i}" )
        break
    fi

    case "$arg" in
        -l) mode=library ;;
        -p) mode=playlist ;;
    esac

    let i++
done

case "$mode" in
    library)
        artist=$(d_artist_composer)
        [[ $artist ]] || exit 1

        album=$(d_album "$artist")

        if [[ $album == "$all_name" || -z $album ]]; then
	    cat <(mpc find composer "$artist") <(mpc find artist "$artist") | sort | mpc add
        else
	    cat <(mpc find composer "$artist" album "$album") <(mpc find artist "$artist" album "$album") | sort | mpc add
        fi

        mpc play >/dev/null 2>&1
    ;;
    playlist)
        mpc play "$(d_playlist)"
    ;;
esac
