#!/bin/bash

all_name='[ALL]'
clear_name='[CLEAR]'
album_name='[ALBUM]'
artist_name='[ARTIST/COMPOSER]'
mode=library

d_library() {
	playlist_length_init=$(mpc playlist | wc -l)
	track=$(mpc listall -f "[%composer% > |%artist% > ][%album% > ][%title%]" | sort -f | cat <(printf '%s\n' "$all_name") <(printf '%s\n' "$artist_name") <(printf '%s\n' "$album_name") - | sed '/^$/d' | dmenu -p Music "${dmenu_args[@]}")
	if [ -z "$track" ]; then
		exit 1
	elif [ $track == "$all_name" ]; then
		mpc listall | mpc add
	elif [ $track == "$artist_name" ]; then
		artist=$(d_artist_composer)
        	[[ $artist ]] || exit 1
		if [[ $artist == "$all_name" ]]; then
			cat <(mpc list artist) <(mpc list composer) | sort -f | mpc add
		fi	
		album=$(d_album "$artist")
		[[ $album ]] || exit 1
        	if [[ $album == "$all_name" ]]; then
		    cat <(mpc find composer "$artist") <(mpc find artist "$artist") | sort | mpc add
        	else
		    cat <(mpc find composer "$artist" album "$album") <(mpc find artist "$artist" album "$album") | sort | mpc add
        	fi
	elif [ $track == "$album_name" ]; then
		album=$(d_album)
		[[ $album ]] || exit 1
		if [[ $album == "$all_name" ]]; then
			mpc list album | mpc add
		else
			mpc find album "$album" | mpc add
		fi
	else
		IFS='>' read -r track_split_1 track_split_2 track_split_3 <<< "$track"
		track_composer="$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' <<< ${track_split_1})"
		track_album="$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' <<< ${track_split_2})"
		track_title="$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' <<< ${track_split_3})"
		mpc search any "$track_composer" any "$track_album" any "$track_title" | mpc add
	fi
	playlist_length_current=$(mpc playlist | wc -l)
	number_added_items=$(($playlist_length_current - $playlist_length_init))
	mpc play $((($playlist_length_current - $number_added_items) + 1)) >/dev/null 2>&1
}

d_artist_composer() {
	cat <(mpc list artist) <(mpc list composer) | sort -f | cat <(printf '%s\n' "$all_name") - | sed '/^$/d' | dmenu -p Artist/Composer: "${dmenu_args[@]}"
}

d_album() {
    local artist="$1"
    local albums

    mapfile -t albums < <(cat <(mpc list album composer "$artist") <(mpc list album artist "$artist") | sort -f | uniq | sed '/^$/d')
    if [[ ${#albums[@]} > 1 ]]; then
        {
            printf '%s\n' "$all_name"
            printf '%s\n' "${albums[@]}" | sort -f
        } | dmenu -p "$artist Album:" "${dmenu_args[@]}"
    else
        # We only have one album, so just use that.
        printf '%s\n' "${albums[0]}"
    fi
}

d_playlist() {
    local format="%position%[[[ - %title%][ - %album%][ - %composer% | - %artist%]] | [ - %file%]]"
    local track
    track=$(cat <(printf '%s\n' "$clear_name") <(mpc playlist -f "$format") | dmenu -p Playlist: "${dmenu_args[@]}")
    playlist=$(printf '%s' "${track%% *}")
    if [[ $playlist == "$clear_name" ]]; then
	mpc clear
    else
        mpc play "$playlist"
    fi
}

i=2
for arg do
    if [[ $arg == :: ]]; then
        dmenu_args=( "${@:$i}" )
        break
    fi

    case "$arg" in
        -l) mode=library ;;
        -p) mode=playlist ;;
    esac

    let i++
done

case "$mode" in
    library)
	$(d_library)
    ;;
    playlist)
	$(d_playlist)
    ;;
esac
